#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_3(
        KC_B, KC_L, KC_D, KC_W, KC_Z, KC_QUOT, KC_F, KC_O, KC_U, KC_J,
        KC_N, KC_R, KC_T, KC_S, KC_G, KC_Y, KC_H, KC_A, KC_E, KC_I,
        LCTL_T(KC_Q), LSFT_T(KC_X), KC_M, KC_C, KC_V, KC_K, KC_P, KC_COMM, RSFT_T(KC_DOT), RCTL_T(KC_SLSH),
        KC_LGUI, KC_SPC, MO(1), MO(2), KC_ENT, KC_RALT
    ),
    [1] = LAYOUT_split_3x5_3(
        KC_ESC, KC_TAB, LCTL(KC_A), KC_NO, LCTL(KC_F), KC_GRV, KC_NO, KC_LBRC, KC_RBRC, KC_BSPC,
        KC_NO, TO(3), TO(4), TO(5), TO(6), KC_NO, KC_SCLN, KC_LPRN, KC_RPRN, KC_BSLS,
        LCTL_T(KC_NO), LSFT_T(KC_NO), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MINS, RSFT_T(KC_EQL), RCTL_T(KC_NO),
        KC_LGUI, KC_LALT, KC_TRNS, KC_NO, KC_ENT, KC_RALT
    ),
    [2] = LAYOUT_split_3x5_3(
        KC_NO, KC_NO, KC_HOME, KC_END, KC_PGUP, KC_NO, KC_7, KC_8, KC_9, KC_BSPC,
        KC_NO, KC_LEFT, KC_UP, KC_RGHT, KC_PGDN, KC_NO, KC_4, KC_5, KC_6, KC_NO,
        LCTL_T(KC_NO), LSFT_T(KC_NO), KC_DOWN, KC_NO, KC_NO, KC_0, KC_1, KC_2, RSFT_T(KC_3), RCTL_T(KC_NO),
        KC_LGUI, KC_SPC, KC_NO, KC_TRNS, KC_ENT, KC_RALT
    ),
    [3] = LAYOUT_split_3x5_3(
        KC_NO, KC_NO, KC_MPRV, KC_MNXT, KC_VOLU, KC_NO, KC_F7, KC_F8, KC_F9, KC_F10,
        KC_NO, KC_NO, RGB_VAI, KC_SLEP, KC_VOLD, KC_NO, KC_F4, KC_F5, KC_F6, KC_F11,
        RGB_HUD, RGB_SAD, RGB_VAD, KC_NO, KC_MPLY, KC_NO, KC_F1, KC_F2, KC_F3, KC_F12,
        KC_LGUI, KC_SPC, TO(0), KC_TRNS, KC_ENT, KC_RALT
    ),
    [4] = LAYOUT_split_3x5_3(
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        KC_NO, KC_NO, TO(0), KC_NO, KC_NO, KC_NO
    ),
    [5] = LAYOUT_split_3x5_3(
        KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P,
        KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN,
        KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
        KC_NO, KC_SPC, TO(0), KC_NO, KC_ENT, KC_NO
    ),
    [6] = LAYOUT_split_3x5_3(
        KC_B, KC_L, KC_D, KC_W, KC_Z, KC_QUOT, KC_F, KC_O, KC_U, KC_J,
        KC_N, KC_LEFT, KC_UP, KC_RGHT, KC_G, KC_Y, KC_H, KC_A, KC_E, KC_I,
        KC_F3, KC_X, KC_DOWN, KC_C, KC_V, KC_K, KC_P, KC_COMM, KC_DOT, KC_SLSH,
        KC_NO, KC_SPC, KC_NO, KC_ESC, KC_ENT, TO(0)
    )
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
